spring.application.name=food


server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Food_Order
spring.datasource.username=postgres
spring.datasource.password=sumai123
spring.datasource.driver-class-name=org.postgresql.Driver